pkg/sandbox/sidecar/envoy.go
pkg/sandbox/sidecar/set_cookie_tpl.go
pkg/sandbox/sidecar/sidecar.go
pkg/webhook/webhook.go

/kind bug
fixed kubelet probe failed with envoy redirect

kubelet probe failed with envoy redirect

---

controllers/appmgr_controller.go

/kind bug
fixed: the failed installation operation did not clean up the resources

fixed: the failed installation operation did not clean up the resources

---

controllers/appmgr_controller.go

/kind bug
fix: replace delete namespace directly with uninstall
Fixes #
```release-note
```

fix: replace delete namespace directly with uninstall

---

pkg/apiserver/handler_upgrade.go
pkg/upgrade/version.go

/kind bug
fit terminus release version return
Fixes #
```release-note
```

fix: upgrader version

---

pkg/apiserver/handler_installer.go

/kind bug
correct recommend upgrade operate type
Fixes #
```release-note
```

fix: recommend upgrade operate log

---

pkg/users/userspace/v1/create.go

/kind bug
fix: set gpu type when create new user
Fixes #
```release-note
```

fix: set gpu type when create new user

---

controllers/application_controller.go
pkg/apiserver/handler_settings.go
pkg/appinstaller/helm.go

/kind bug
fix: upgrade app with entrance does not update app etrances
Fixes #
```release-note
```

fix: upgrade app with entrance does not update app etrances

---

controllers/application_controller.go
pkg/apiserver/handler_settings.go
pkg/appinstaller/helm.go

/kind refactor
refactor entrance,policy create,update
Fixes #
```release-note
```

refactor entrance,policy create,update

---

controllers/appmgr_controller.go
pkg/utils/app.go

/kind bug
add retry for update crd confilict
Fixes #
```release-note
```

add retry for update crd confilict

---

pkg/tapr/middleware_request_util.go

/kind bug
fix: create or update middleware request
Fixes #
```release-note
```

fix: create or update middleware request

---

pkg/helm/helm.go

/kind bug
fix: ignore helm release purge failed error
Fixes #
```release-note
```

fix: ignore helm release purge failed error

---

pkg/helm/helm.go

/kind bug
fix: chart uninstall res check
Fixes #
```release-note
```

fix: chart uninstall res check

---

pkg/apiserver/utils.go

/kind bug
fix: optimize resource not satisfied msg
Fixes #
```release-note
```

fix: optimize resource not satisfied msg

---

controllers/appmgr_controller.go

/kind bug
fix: install panic with uninit helmops
Fixes #
```release-note
```

fix: install panic with uninit helmops

---

controllers/appmgr_controller.go
controllers/image_controller.go
go.mod
go.sum
pkg/images/jobs.go
pkg/images/puller.go
pkg/utils/helm.go

/kind bug
fix:  image download progress rollback;install hang cause by crd imagemanager update error
Fixes #
```release-note
```

fix: image download progress rollback;install hang cause by crd imagemanager update error

---

controllers/image_controller.go

/kind bug
fix: let error to download step
Fixes #
```release-note
```

fix: let error to download step

---

pkg/tapr/middleware_request_tpl.go
pkg/tapr/middleware_request_tpl_test.go
pkg/tapr/middleware_types.go

/kind feature
postgresql add support extension and execute script;mongo add support execute script
Fixes #
```release-note
```

feat: postgresql support extension and execute script;mongo support execute script

---

pkg/upgrade/github.go
pkg/upgrade/jobs.go

fix: get upgrade release version from terminus space

---

controllers/application_controller.go
pkg/apiserver/handler_installer.go
pkg/appinstaller/appcfg_types.go
pkg/appinstaller/appcfg_utils.go
pkg/appinstaller/application.go
pkg/constants/constants.go

/kind feature
add config for mobileSupported in TerminusManifest.yaml
Fixes #
```release-note
```

feat: add config for mobileSupported

---

.github/workflows/publish_docker.yaml
.github/workflows/publish_imageservice.yaml
.github/workflows/publish_upgrader.yaml
Dockerfile
Dockerfile.image
Dockerfile.job

/kind feature
add arm64 arch support
Fixes #
```release-note
```

feat: add arm support

---

api/app.bytetrade.io/v1alpha1/appmanager_states.go
api/app.bytetrade.io/v1alpha1/appmanager_types.go
controllers/application_controller.go
controllers/image_controller.go
pkg/apiserver/handler_app.go
pkg/apiserver/handler_appupgrade.go
pkg/apiserver/handler_installer.go
pkg/apiserver/handler_middleware.go
pkg/apiserver/handler_middleware_status.go
pkg/apiserver/handler_prometheus.go
pkg/apiserver/handler_recommend_status.go
pkg/apiserver/handler_service.go
pkg/apiserver/handler_suspend.go
pkg/apiserver/utils.go
pkg/apiserver/webservice.go
pkg/appinstaller/appcfg_types.go
pkg/appinstaller/appcfg_utils.go
pkg/appinstaller/application.go
pkg/appinstaller/helm.go
pkg/constants/constants.go
pkg/images/jobs.go
pkg/images/puller.go
pkg/middlewareinstaller/installer.go
pkg/middlewareinstaller/middleware_cfg.go
pkg/middlewareinstaller/request.go
pkg/users/userspace/v1/create.go
pkg/utils/app.go
pkg/utils/k8sutil.go

/kind feature
support middleware install;set namespace for an app
Fixes #
```release-note
```

feat: support middleware install;set namespace

---

pkg/apiserver/handler_installer.go
pkg/utils/app.go

/kind bug
fix: forbid install namespace
Fixes #
```release-note
```

fix: forbid install namespace

---

pkg/apiserver/handler_middleware_status.go

/kind bug
fix: middleware status data returns null
Fixes #
```release-note
```

fix: middleware status data returns null

---

pkg/apiserver/handler_installer.go

/kind bug
fix: recommend upgrade with failed state
Fixes #
```release-note
```

fix: recommend upgrade with failed state

---

pkg/apiserver/handler_model.go

/kind bug
fix: change dify url
Fixes #
```release-note
```

fix: change dify url

---

pkg/apiserver/handler_webhook.go
pkg/constants/constants.go
pkg/provider/application_permission.go
pkg/provider/request.go
pkg/sandbox/sidecar/envoy.go
pkg/sandbox/sidecar/sidecar.go
pkg/webhook/webhook.go

/kind refactor
refactor: legacy api with envoy sidecar
Fixes #
```release-note
```

refactor: legacy api with envoy sidecar

---

pkg/sandbox/sidecar/envoy.go

/kind bug
fix: missing outbound listener
Fixes #
```release-note
```

fix: missing outbound listener

---

pkg/apiserver/handler_settings.go
pkg/apiserver/webservice.go
pkg/sandbox/sidecar/envoy.go

/kind feature
add application permissions api
Fixes #
```release-note
```

feat: add application permissions api

---

pkg/apiserver/handler_settings.go

/kind bug
fix: return http status when application permission not found
Fixes #
```release-note
```

fix: return http status

---

pkg/apiserver/filters.go
pkg/apiserver/handler.go
pkg/apiserver/handler_installer.go
pkg/apiserver/handler_webhook.go
pkg/apiserver/webservice.go
pkg/appinstaller/appcfg_types.go
pkg/appinstaller/appcfg_utils.go
pkg/appinstaller/application.go
pkg/sandbox/sidecar/envoy.go
pkg/webhook/setup.go
pkg/webhook/webhook.go

/kind bug
app inter call envoy sidecar inject;webhook check provider registry
Fixes #
```release-note
```

fix: app inter call envoy sidecar inject;webhook check provider registry

---

pkg/apiserver/handler_webhook.go
pkg/sandbox/sidecar/envoy.go

/kind bug
add origin_dst for not matched host
Fixes #
```release-note
```

fix: add origin_dst for not matched host

---

pkg/sandbox/sidecar/envoy.go
pkg/utils/helm.go

/king bug
fix: image ref resolver error
Fixes #
```release-note
```

fix: image ref resolver error

---

pkg/webhook/webhook.go

/kind bug
fix: add runtime_class_name for nvidia gpu type
Fixes #
```release-note
```

fix: add runtime_class_name for nvidia gpu type

---

pkg/appinstaller/helm.go
pkg/users/userspace/v1/create.go
pkg/utils/helm.go

/kind feature
add cluster arch for helm values
Fixes #
```release-note
```

feat: add cluster arch for helm values

---

pkg/apiserver/handler_settings.go
pkg/apiserver/webservice.go

/kind feature
add get provider registry list by appname api
Fixes #
```release-note
```

feat: get provider registry list by appname

---

pkg/apiserver/handler_settings.go

/kind bug
fix: provider list add field version
Fixes #
```release-note
```

fix: provider list add field version

---

controllers/appmgr_controller.go
pkg/apiserver/handler_settings.go
pkg/apiserver/webservice.go
pkg/sandbox/sidecar/envoy.go
pkg/tapr/middleware.go
pkg/tapr/middleware_request_tpl.go
pkg/tapr/middleware_request_tpl_test.go
pkg/tapr/middleware_types.go
pkg/utils/helm.go
pkg/utils/tools.go

/kind feature
add support for nats
Fixes #
```release-note
```

feat: add support for nats

---

pkg/utils/helm.go

/kind bug
fix: set oidc values
Fixes #
```release-note
```

fix: set oidc values

---

pkg/sandbox/sidecar/envoy.go
pkg/webhook/webhook.go

/kind feature
add wait-for init container
Fixes #
```release-note
```

feat: wait-for init container

---

pkg/appinstaller/helm.go

/kind bug
fix: create namespce for oidc secret
Fixes #
```release-note
```

fix: create namespce for oidc secret

---

controllers/application_controller.go

fix: appid bug

---

pkg/apiserver/handler_settings.go
pkg/tapr/middleware_request_tpl.go
pkg/tapr/middleware_request_tpl_test.go
pkg/tapr/middleware_types.go

/kind bug
fix: change nats export to array
Fixes #
```release-note
```

fix: change nats export to array

---

pkg/apiserver/handler_app.go
pkg/apiserver/webservice.go

/kind feature
feat: return all user's app for admin user
Fixes #
```release-note
```

feat: return all user's app for admin

---

pkg/apiserver/handler_appupgrade.go
pkg/helm/helm.go

/kind bug
fix: upgrade does not update envoy config and recreate pod
Fixes #
```release-note
```

fix: upgrade does not update envoy config

---

pkg/utils/tools.go

/kind bug
fix: avoid a random string with leading digit or $
Fixes #
```release-note
```

fix: avoid a random string with leading digit or $

---

pkg/images/jobs.go
pkg/sandbox/sidecar/envoy.go

/kind bug
fix: change retry strategy
Fixes #
```release-note
```

fix: change retry strategy

---

pkg/apiserver/handler_app.go

/kind bug
fix: sub account can visit it apps
Fixes #
```release-note
```

fix: sub account can visit it apps

---

controllers/application_controller.go
pkg/constants/constants.go
pkg/utils/app.go

/kind feature
feat: support define multi sys app in single deployment,statefulset
Fixes #
```release-note
```

feat: support define multi sys app in single deployment,statefulset

---

controllers/application_controller.go
pkg/apiserver/handler_settings.go
pkg/appinstaller/helm.go

/kind feat
feat: support auth default policy system
Fixes #
```release-note
```

feat: support auth default policy system

---

pkg/utils/app.go

/kind bug
fix: sys appmgr created with no status field
Fixes #
```release-note
```

fix: sys appmgr created with no status field

---

controllers/appmgr_controller.go
pkg/appinstaller/helm.go

/kind feature
feat: add label for imagemanager resource
Fixes #
```release-note
```

feat: add label for imagemanager resource

---

api/app.bytetrade.io/v1alpha1/application_types.go
config/crd/bases/app.bytetrade.io_applications.yaml
config/crd/bases/app.bytetrade.io_imagemanagers.yaml

/kind feature
feat: app entrance add window push state field
Fixes #
```release-note
```

feat: app entrance add window push state field

---

pkg/appinstaller/helm.go

/kind feature
feat: set values for sharedlib path
Fixes #
```release-note
```

feat: set values for sharedlib path

---

pkg/apiserver/handler_app.go
pkg/constants/constants.go

/kind bug
fix: set correct app status when only applicatonmanagers exists
Fixes #
```release-note
```

fix: set correct app status when only applicatonmanagers exists

---

controllers/image_controller.go
pkg/images/jobs.go
pkg/images/puller.go

/kind bug
fix: pull image support containerd cri mirrors endpoint
Fixes #
```release-note
```

fix: pull image support containerd cri mirrors endpoint

---

controllers/appmgr_controller.go
pkg/apiserver/filters.go
pkg/apiserver/handler.go
pkg/apiserver/handler_webhook.go
pkg/apiserver/webservice.go
pkg/utils/k8sutil.go
pkg/webhook/setup.go

/kind feature
feat: set deploy/sts replicase to zero when cluster node num eq zero
Fixes #
```release-note
```

feat: set deploy/sts replicas to zero when cluster node num eq zero

---

pkg/images/jobs.go

/kind bug
fix: image manager statusTime
Fixes #
```release-note
```

fix: image manager statusTime

---

pkg/sandbox/sidecar/envoy.go

/kind bug
fix: envoy outbound upgrade websocket
Fixes #
```release-note
```

fix: envoy outbound upgrade websocket

---

pkg/sandbox/sidecar/envoy.go

/kind bug
fix: envoy timeout
Fixes #
```release-note
```

fix: envoy timeout

---

pkg/sandbox/sidecar/envoy.go

/kind bug
fix: change probes route from prefix to path match
Fixes #
```release-note
```

fix: change probes route from prefix to path match

---

pkg/apiserver/filters.go
pkg/apiserver/handler.go
pkg/apiserver/handler_webhook.go
pkg/apiserver/webservice.go
pkg/webhook/setup.go

/kind bug
fix: eviction from kubelet
Fixes #
```release-note
```

fix: eviction from kubelet

---

pkg/apiserver/handler_webhook.go

/kind bug
fix: use decode pod info instead get operation
Fixes #
```release-note
```

fix: use decode pod info instead get operation

---

pkg/apiserver/handler_installer.go

/kind bug
fix: remove dep app check when uninstall
Fixes #
```release-note
```

fix: remove dep app check when uninstall

---

pkg/images/jobs.go

/kind bug
fix: correct image progress when in no need pull situation
Fixes #
```release-note
```

fix: correct image progress when in no need pull situation

---

pkg/images/jobs.go
pkg/images/puller.go

/kind bug
fix: change pull image retry strategy
Fixes #
```release-note
```

fix: change pull image retry strategy

---

controllers/appmgr_controller.go
pkg/images/jobs.go
pkg/images/puller.go

/kind bug
fix: fluently and correct image download progress
Fixes #
```release-note
```

fix: fluently and correct image download progress

---

pkg/images/jobs.go

/kind bug
fix: image layer count
Fixes #
```release-note
```

fix: image layer count

---

pkg/images/puller.go

/kind bug
fix: empty registry
Fixes #
```release-note
```

fix: empty registry

---

go.mod
go.sum
pkg/apiserver/filters.go
pkg/apiserver/handler.go
pkg/apiserver/handler_webhook.go
pkg/apiserver/webservice.go
pkg/images/puller.go
pkg/utils/k8sutil.go
pkg/webhook/setup.go

/kind feature
feat: change cron workflow container image when use mirrors
Fixes #
```release-note
```

feat: change cron workflow container image when use mirrors

---

controllers/appmgr_controller.go
pkg/images/jobs.go

/kind bug
fix: more smooth progress cal method
Fixes #
```release-note
```

fix: more smooth progress cal method

---

pkg/images/jobs.go

/kind bug
fix: set pulled image status
Fixes #
```release-note
```

fix: set pulled image status

---

pkg/apiserver/handler_service.go

/kind bug
fix: add downloading app to list
Fixes #
```release-note
```

fix: add downloading app to list

---

pkg/webhook/setup.go

/kind bug
fix: replace image repo when update cwf
Fixes #
```release-note
```

fix: replace image repo when update cwf

---

pkg/upgrade/jobs.go

fix: failed to download upgrade package from github

---

controllers/appmgr_controller.go

/kind bug
fix: suspend app in user-space cause all deploy replicas set to 0 in that namespace
Fixes #
```release-note
```

fix: suspend app in user-space cause all deploy replicas set to 0 in that namespace

---

controllers/entrancestatus_controller.go

/kind bug
fix: multi app in one deploy/sts
Fixes #
```release-note
```

fix: multi app in one deploy/sts

---

pkg/upgrade/version.go

/kind fix
fix: set space url from env
Fixes #
```release-note
```

fix: space url

---

pkg/utils/helm.go

/kind bug
fix: crds dry run panic
Fixes #
```release-note
```

fix: crds dry run panic

---

controllers/appmgr_controller.go
pkg/constants/constants.go

/king bug
fix: delete appcahce dir with error
Fixes #
```release-note
```

fix: delete appcahce dir with error

---

pkg/apiserver/handler_webhook.go
pkg/webhook/webhook.go

/kind bug
fix: webhook response with uid
Fixes #
```release-note
```

fix: webhook response with uid

---

controllers/entrancestatus_controller.go
pkg/apiserver/handler_appupgrade.go
pkg/apiserver/handler_installer.go
pkg/apiserver/info.go
pkg/apiserver/utils.go
pkg/appinstaller/appcfg_types.go
pkg/appinstaller/appcfg_utils.go

/kind refactor
fix: change app cfg filename
Fixes #
```release-note
```

fix: change app cfg filename

---

pkg/appinstaller/helm.go
pkg/users/userspace/v1/create.go

/kind bug
fix: add rootPath for helm values
Fixes #
```release-note
```

fix: add rootPath for helm values

---

pkg/appwatchers/suspend.go
pkg/prometheus/prometheus.go
pkg/prometheus/prometheus_types.go

/kind feature
feat: add cluster and user cpu threshold for suspend app
Fixes #
```release-note
```

feat: add cluster and user cpu threshold for suspend app

---

controllers/entrancestatus_controller.go

/kind bug
fix: app state with crash but pod is running
Fixes #
```release-note
```

fix: app state with crash but pod is running

---

pkg/apiserver/handler_webhook.go
pkg/images/puller.go
pkg/utils/k8sutil.go

/kind bug
fix: add support for http mirror
Fixes #
```release-note
```

fix: add support for http mirror

---

pkg/apiserver/handler_gpu.go

/kind bug
fix: nvshare switch not update deployment with gpu
Fixes #
```release-note
```

fix: nvshare switch not update deployment

---

pkg/apiserver/filters.go
pkg/apiserver/handler.go
pkg/apiserver/handler_webhook.go
pkg/apiserver/webservice.go
pkg/webhook/setup.go

/kind feature
feat: inject runasuser equal 1000 for third party app's pod
Fixes #
```release-note
```

feat: inject runasuser equal 1000 for third party app's pod

---

pkg/appinstaller/helm.go

/kind bug
fix: rm unmanaged pvc before unintall
Fixes #
```release-note
```

fix: rm unmanaged pvc before unintall

---

pkg/apiserver/handler_gpu.go
pkg/upgrade/github.go

/kind bug
fix: set github base url by olares space url
Fixes #
```release-note
```

fix: set github base url by olares space url

---

pkg/apiserver/handler_upgrade.go

/kind bug
fix: propagate space url to upgrade job env
Fixes #
```release-note
```

fix: propagate space url to upgrade job env

---

pkg/apiserver/filters.go

/kind bug
fix: api terminus version disable authn
Fixes #
```release-note
```

fix: api terminus version disable authn

---

pkg/apiserver/utils.go

/kind bug
fix: metric values length is 0
Fixes #
```release-note
```

fix: metric values length is 0

---

controllers/appmgr_controller.go

/kind bug
fix: cancel op patch imagemanager status error
Fixes #
```release-note
```

fix: cancel op patch imagemanager status error

---

pkg/apiserver/filters.go
pkg/apiserver/handler.go
pkg/apiserver/handler_webhook.go
pkg/apiserver/webservice.go
pkg/appinstaller/helm.go
pkg/webhook/setup.go

/kind bug
fix: patch deploy/sts pod template cause pod restart
Fixes #
```release-note
```

fix: patch deploy/sts pod template cause pod restart

---

controllers/appmgr_controller.go
pkg/images/jobs.go

/kind bug
fix: correct image download offset
Fixes #
```release-note
```

fix: correct image download offset

---

controllers/appmgr_controller.go

/kind bug
fix: suspend app in os-system namespace
Fixes #
```release-note
```

fix: suspend app in os-system namespace

---

pkg/apiserver/handler_service.go
pkg/constants/constants.go

/kind feature
fix: missing app state initializing
Fixes #
```release-note
```

fix: missing app state initializing

---

pkg/images/puller.go
pkg/utils/k8sutil.go

/kind bug
fix: omit replace with mirrors if registry not equal docker.io
Fixes #
```release-note
```

fix: omit replace with mirrors if registry not equal docker.io

---

controllers/application_controller.go

/kind bug
fix: multi app creation may failed
Fixes #
```release-note
```

fix: multi app creation may failed

---

controllers/application_controller.go
controllers/appmgr_controller.go
pkg/apiserver/api/errors.go
pkg/apiserver/handler_installer.go
pkg/apiserver/utils.go
pkg/appinstaller/appcfg_types.go
pkg/appinstaller/helm.go

/kind feature
feat: add mandatory dep check; dequeue when app is initialized
Fixes #
```release-note
```

feat: add mandatory dep check; dequeue when app is initialized

---

controllers/tailscale_acl_controller.go

/kind bug
fix: no need to rolling update headscale when no acls need apply
Fixes #
```release-note
```

fix: no need to rolling update headscale when no acls need apply

---

controllers/appmgr_controller.go
pkg/apiserver/api/errors.go
pkg/apiserver/handler_installer.go
pkg/apiserver/handler_suspend.go
pkg/constants/constants.go

/kind bug
fix: add check for some operation
Fixes #
```release-note
```

fix: add check for some operation

---

pkg/constants/constants.go
pkg/webhook/webhook.go

/kind bug
fix: no env exist in yaml cause inject error
Fixes #
```release-note
```

fix: no env exist in yaml cause inject error

---

controllers/appmgr_controller.go
pkg/apiserver/utils.go

/kind bug
fix: increase the request timeout duration
Fixes #
```release-note
```

fix: increase the request timeout duration

---

pkg/apiserver/handler_webhook.go

/kind bug
fix: add nvshare_debug env
Fixes #
```release-note
```

fix: add nvshare_debug env

---

pkg/sandbox/sidecar/envoy.go

/kind bug
fix: set iptables for windows browser network
Fixes #
```release-note
```

fix: set iptables for windows browser network

---

pkg/apiserver/handler_webhook.go

fix: duplicate nvshare env

---

pkg/appinstaller/helm.go
pkg/utils/app.go

fix: remove app cache path on the hosts directly

---

pkg/appinstaller/helm.go

fix: add debug info

---

pkg/sandbox/sidecar/envoy.go

/kind bug
fix: envoy inbound tcp proxy
Fixes #
```release-note
```

fix: envoy inbound tcp proxy

---

controllers/appmgr_controller.go

/kind bug
fix: resume op after restart
Fixes #
```release-note
```

fix: resume op after restart

---

pkg/kubesphere/kubesphere.go
pkg/security/templates.go

/kind feature
feat: support lldap auth
Fixes #
```release-note
```

feat: support lldap auth

---

controllers/tailscale_acl_controller.go

/kind bug
fix: add default acl
Fixes #
```release-note
```

fix: add default acl

---

pkg/security/templates.go

fix: change user space network policy

---

.github/workflows/build_main.yaml
pkg/apiserver/handler_upgrade.go
pkg/upgrade/jobs.go

feat: download upgrade package from cdn setup by env

---

pkg/tapr/middleware.go

/kind bug
fix: add check for middleware request resp code
Fixes #
```release-note
```

fix: add check for middleware request resp code

---

controllers/appmgr_controller.go
pkg/apiserver/handler_installer.go
pkg/appinstaller/application.go
pkg/appinstaller/helm.go
pkg/utils/app.go

/kind bug
fix: app installation can not be canceled after reboot
Fixes #
```release-note
```

fix: app installation can not be canceled after reboot

---

api/app.bytetrade.io/v1alpha1/application_types.go
controllers/appmgr_controller.go
pkg/appinstaller/appcfg_utils.go
pkg/constants/constants.go

/kind feat
feat: tcp udp port gen
Fixes #
```release-note
```

feat: tcp udp port gen

---

pkg/sandbox/sidecar/envoy.go

fix: add idle timeout to original_dst cluster

---

pkg/sandbox/sidecar/envoy.go

/kind bug
fix: envoy outbound port
Fixes #
```release-note
```

fix: envoy outbound port

---

pkg/apiserver/handler_upgrade.go

fix: return success of job status even if the job has been retried

---

pkg/apiserver/handler_webhook.go
pkg/sandbox/sidecar/envoy.go
pkg/webhook/webhook.go

/kind feature
feat: change hostpath with type DirectoryOrCreate owner to 1000 by inject init container
Fixes #
```release-note
```

feat: change hostpath with type DirectoryOrCreate owner to 1000 by inject init container

---

pkg/apiserver/handler_webhook.go
pkg/sandbox/sidecar/envoy.go
pkg/webhook/webhook.go

Reverts beclab/app-service#158

Revert "feat: change hostpath with type DirectoryOrCreate owner to 1000 by inject init container"

---

pkg/apiserver/handler_upgrade.go

/kind bug
fix: set upgrade job ttl to 30 days
Fixes #
```release-note
```

fix: set upgrade job ttl to 30 days

---

pkg/appinstaller/helm.go

/kind feat
feat: add download cdn url for values
Fixes #
```release-note
```

feat: add download cdn url for values

---

pkg/appinstaller/helm.go

/kind bug
fix: upgrade values
Fixes #
```release-note
```

fix: upgrade values

---

controllers/tailscale_acl_controller.go
pkg/sandbox/sidecar/envoy.go

/kind feat
feat: ts-route coredns svc
Fixes #
```release-note
```

feat: ts-route coredns svc

---

controllers/application_controller.go

/kind bug
fix: update application nil tailscale
Fixes #
```release-note
```

fix: update application nil tailscale

---

controllers/appmgr_controller.go
pkg/apiserver/api/types.go
pkg/apiserver/handler_app.go
pkg/apiserver/handler_appupgrade.go
pkg/apiserver/handler_installer.go
pkg/apiserver/utils.go
pkg/apiserver/webservice.go
pkg/appinstaller/appcfg_types.go
pkg/appinstaller/appcfg_utils.go
pkg/appinstaller/application.go
pkg/utils/helm.go

/kind feat
feat: cschart merge
Fixes #
```release-note
```

feat: cschart merge

---

pkg/apiserver/handler_webhook.go
pkg/appinstaller/helm.go

/kind bug
fix:  app install from devbox omit waitfor launch
Fixes #
```release-note
```

fix:  app install from devbox omit waitfor launch

---

pkg/apiserver/handler_webhook.go
pkg/appinstaller/helm.go

/kind bug
fix: app install from devbox omit waitfor launch
Fixes #
```release-note
```

fix: app install from devbox omit waitfor launch

---

pkg/apiserver/handler_webhook.go

/kind bug
fix: simplify logic for non-gpu scenarios
Fixes #
```release-note
```

fix: simplify logic for non-gpu scenarios

---

pkg/users/userspace/v1/create.go

/kind bug
fix: add marketProvider env
Fixes #
```release-note
```

fix: add marketProvider env

---

pkg/apiserver/handler_prometheus.go

/kind bug
fix: add title and state
Fixes #
```release-note
```

fix: add title and state

---

pkg/appinstaller/helm.go

/kind bug
fix: studio dir
Fixes #
```release-note
```

fix: studio dir

---

pkg/apiserver/handler_installer.go
pkg/users/userspace/v1/create.go

/kind bug
fix: create sub user error
Fixes #
```release-note
```

fix: create sub user error

---

pkg/appinstaller/helm.go

/kind bug
Fixes #
```release-note
```

fix: studio dir 

---

pkg/argo/secret.go

/kind cleanup
fix: simplify argo log
Fixes #
```release-note
```

fix: simplify argo log

---

go.mod
go.sum
pkg/utils/app.go
pkg/utils/app_test.go

/kind bug
fix: the app cache directory is not completely deleted in some case
Fixes #
```release-note
```

fix: the app cache directory is not completely deleted in some case

---

pkg/apiserver/handler_upgrade.go

fix: check node status before system upgrade

---

pkg/images/puller.go

/kind bug
fix: pull image with unpack
Fixes #
```release-note
```

fix: pull image with unpack

---

pkg/appinstaller/helm.go
pkg/utils/app.go

/kind bug
fix: cache dir delete call files
Fixes #
```release-note
```

fix: cache dir delete call files

---

pkg/apiserver/handler_webhook.go

/kind bug
fix: inject val to all deploy under app
Fixes #
```release-note
```

fix: inject val to all deploy under app

---

pkg/apiserver/handler_webhook.go

Reverts beclab/app-service#204

Revert "fix: inject val to all deploy under app"

---

pkg/apiserver/handler_installer.go
pkg/appinstaller/helm.go

/kind bug
fix: check operation before install
Fixes #
```release-note
```

fix: check operation before install

---

pkg/apiserver/handler_webhook.go

/kind bug
fix: inject gpu only when app gpu required and deploy been annotation
Fixes #
```release-note
```

fix: inject gpu only when app gpu required and deploy been annotation

---

controllers/security_controller.go

/kind bug
fix: mark the underlay namespace as the system namespace
Fixes #
```release-note
```

fix: mark the underlay namespace as the system namespace

---

pkg/utils/helm.go

/kind bug
fix: filter normalized image ref
Fixes #
```release-note
```

fix: filter normalized image ref

---

controllers/appmgr_controller.go
pkg/images/jobs.go

/kind bug
fix: pull exists image not update progress correct
Fixes #
```release-note
```

fix: pull exists image not update progress correct

---

cmd/app-service/main.go
pkg/apiserver/apiserver.go
pkg/apiserver/handler.go
pkg/apiserver/handler_app.go

/kind feat
feat: add cache for app appmgr
Fixes #
```release-note
```

feat: add cache for app appmgr

---

pkg/users/userspace/v1/create.go

/kind bug
fix: add COREDNS_SVC for sub user tailscale
Fixes #
```release-note
```

fix: add COREDNS_SVC for sub user tailscale

---

controllers/entrancestatus_controller.go

/kind bug
fix: entrance status may loss event after reboot
Fixes #
```release-note
```

fix: entrance status may loss event after reboot

---

pkg/apiserver/handler_webhook.go

/kind feat
feat: add app,olares name for pod
Fixes #
```release-note
```

feat: add app,olares name for pod

---

pkg/appinstaller/helm.go
pkg/appstate/state_transition.go

/kind bug
fix: upgrade failed
Fixes #
```release-note
```

fix: upgrade failed

---

pkg/kubesphere/kubesphere.go
pkg/users/userspace/v1/create.go
pkg/utils/iputils.go

/kind feat
feat: inject env for tailscale
Fixes #
```release-note
```

feat: inject env for tailscale

---

controllers/tailscale_acl_controller.go

fix: add tailscale acl

---

controllers/tailscale_acl_controller.go

/kind bug
fix: remove node ip from subroute
Fixes #
```release-note
```

fix: remove node ip from subroute

---

controllers/application_controller.go
pkg/apiserver/handler_app.go
pkg/appcfg/application.go
pkg/appcfg/utils.go
pkg/appinstaller/helm.go
pkg/constants/constants.go
pkg/utils/app/app.go

/kind feat
feat: add gpu required field
Fixes #
```release-note
```

feat: add gpu required field

---

controllers/appmgr_controller.go
pkg/appstate/errors.go
pkg/appstate/factory.go
pkg/appstate/pending_app.go

fix: limit concurrent downloading app

---

api/app.bytetrade.io/v1alpha1/appmanager_states.go
controllers/appmgr_controller.go
pkg/appstate/download_canceling_app.go
pkg/appstate/downloading_app.go
pkg/appstate/initializing_app.go
pkg/appstate/initializing_canceling_app.go
pkg/appstate/installing_app.go
pkg/appstate/installing_canceling_app.go
pkg/appstate/pending_canceling_app.go
pkg/appstate/resuming_app.go
pkg/appstate/resuming_canceling_app.go
pkg/appstate/types.go
pkg/appstate/uninstalling_app.go
pkg/appstate/upgrading_app.go

fix: missing ttl option

---

pkg/webhook/setup.go

/kind bug
Fixes #
```release-note
```

fix: remove l4 proxy hostnetwork limit

---

pkg/apiserver/handler_service.go

/kind bug
Fixes #
```release-note
```

fix: userapps api

---

pkg/apiserver/handler_user.go
pkg/apiserver/handler_webhook.go
pkg/apiserver/utils.go

/kind bug
Fixes #
```release-note
```

fix: some api of user create

---

controllers/appmgr_controller.go
pkg/appinstaller/helm.go
pkg/workflowinstaller/installer.go

/kind bug
fix: workflow install
Fixes #
```release-note
```

fix: workflow install

---

controllers/user_controller.go
pkg/apiserver/handler_user.go
pkg/users/templates.go
pkg/utils/nats.go

/kind feat
feat: publish user event to nats
Fixes #
```release-note
```

feat: publish user event to nats

---

pkg/appinstaller/helm_utils.go
pkg/utils/app_utils.go

/kind bug
fix: add fs_type to values
Fixes #
```release-note
```

fix: add fs_type to values

---

pkg/apiserver/handler_app.go
pkg/apiserver/handler_service.go
pkg/apiserver/handler_settings.go

/kind bug
fix: change to new chart repo
Fixes #
```release-note
```

fix: change to new chart repo

---

controllers/user_controller.go

/kind bug
Fixes #
```release-note
```

fix: user does not sync to lldap

---

controllers/application_controller.go

/kind bug
Fixes #
```release-note
```

fix: deploy was deleted fault

---

pkg/apiserver/filters.go
pkg/apiserver/handler_app.go

/kind bug
Fixes #
```release-note
```

fix: add url pass auth filter

---

controllers/user_controller.go

/king bug
Fixes #
```release-note
```

fix: add conflict retry and add some log

---

pkg/appstate/factory.go
pkg/appstate/pending_app.go
pkg/images/client.go

fix: limit downloading app

---

pkg/users/userspace/v1/create.go

/kind bug
Fixes #
```release-note
```

fix: user create is pending

---

pkg/apiserver/handler_installer_upgrade.go
pkg/appcfg/utils.go
pkg/appinstaller/v2/helm_ops_upgrade.go
pkg/appstate/downloading_app.go
pkg/appstate/upgrading_app.go

/kind bug
fix: upgradev2 and values.admin
Fixes #
```release-note
```

fix: upgradev2 and values.admin

---

pkg/appstate/pending_app.go

/kind bug
fix: set max downloading to 1
Fixes #
```release-note
```

fix: set max downloading to 1

---

controllers/user_controller.go
pkg/apiserver/handler_user.go
pkg/apiserver/handler_webhook.go
pkg/utils/k8sutil.go

/kind bug
fix: add support for creator cli
Fixes #
```release-note
```

fix: add support for creator cli

---

pkg/users/userspace/v1/create.go

/kind bug
Fixes #
```release-note
```

fix: remove ks redis secret

---

controllers/image_info_controller.go
pkg/apiserver/api/types.go
pkg/apiserver/handler_installer_image_info.go

/kind bug
Fixes #
```release-note
```

fix: improve performance of retrieving image layer information

---

pkg/apiserver/handler_service.go
pkg/appstate/upgrading_app.go
pkg/images/jobs.go

/kind bug
fix: app sort and app upgrade chart render
Fixes #
```release-note
```

fix: app sort and app upgrade chart render

---

controllers/application_controller.go
pkg/apiserver/handler_settings.go

/kind bug
fix: set up entrance id upgrade
Fixes #
```release-note
```

fix: set up entrance id upgrade

---

api/app.bytetrade.io/v1alpha1/helper.go
go.mod
go.sum
pkg/apiserver/handler.go
pkg/apiserver/handler_installer_install.go
pkg/apiserver/handler_installer_install_recommend.go
pkg/apiserver/handler_installer_uninstall.go
pkg/apiserver/handler_installer_upgrade.go
pkg/apiserver/handler_middleware.go
pkg/apiserver/handler_prometheus.go
pkg/apiserver/handler_settings.go
pkg/appinstaller/helm_ops_install.go
pkg/sandbox/sidecar/envoy.go
pkg/utils/app/provider.go
pkg/utils/k8sutil.go
pkg/webhook/webhook.go

fix: envoy config bugs

---

cmd/app-service/main.go
controllers/entrancestatus_controller.go
controllers/load.go
controllers/user_controller.go
pkg/apiserver/handler_app.go
pkg/apiserver/handler_installer_cancel.go
pkg/apiserver/handler_installer_install.go
pkg/apiserver/handler_installer_uninstall.go
pkg/apiserver/handler_installer_upgrade.go
pkg/apiserver/handler_middleware.go
pkg/apiserver/handler_suspend.go
pkg/apiserver/handler_webhook.go
pkg/appstate/pending_app.go
pkg/appstate/types.go
pkg/event/event.go
pkg/images/client.go
pkg/utils/nats.go

/kind bug
fix: publish event from async to sync
Fixes #
```release-note
```

fix: publish event from async to sync

---

pkg/appinstaller/helm_utils.go
pkg/appstate/downloading_app.go
pkg/appstate/upgrading_app.go
pkg/utils/k8sutil.go

fix: add values sysVersion

---

controllers/node_alert_controller.go

/king bug
fix: publish multi event under pressure
Fixes #
```release-note
```

fix: publish multi event under pressure

---

controllers/image_info_controller.go
pkg/images/client.go
pkg/images/puller.go

/kind bug
Fixes #
```release-note
```

fix: catch docker ref parse error

---

pkg/utils/app/app.go
pkg/utils/encrypt.go

refactor: remove nonce key from Chart-Repo request
